### ISSUE TITLE
Icons for apps and may be for methods

### ISSUE THREAD

**Issue by rsutormin** [kbase/narrative_method_store#3]
Jim Thomason:
I spoke with Michael briefly about adding in an icon field to the method store. We agreed to add on an extra field (“icon”) to the return from get_app_full_info, just as part of the blob (same level as “screenshots”).
It should be a string with a path to an image, assumed to be held on the same server as the screenshots or which the narrative is running on, so I can just plop the path directly into place.
I don’t think we need icons for methods, but Paramvir can chime in.
Since we don’t actually even have any icons, there’s no urgency as far as I’m concerned to get this change deployed. I’m going to rewire the front end to use the field if it exists, and otherwise fall back on the kbase logo if it doesn’t, as I’ve been doing now. That said, we should also define a better generic placeholder icon to use, or possibly just use no icon if none exists.

**Comment by msneddon** [comment]
added in fbfbd6ea9995bc7b3034cb711519ba4206983ca9
